# Buildpack API version
api = "0.2"

# Buildpack ID and metadata
[buildpack]
id = "com.vmware.buildpacks.cpp"
version = "0.0.1"
name = "C/C++ Buildpack"

# Stacks that the buildpack will work with
[[stacks]]
id = "io.buildpacks.stacks.bionic"